name: Release Workflow

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Release tag"
        required: true
        type: string
        default: "0.0.0"

jobs:
  build-and-upload-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Find the generated zip file
        run: |
          version=$(jq -r .version package.json)
          zip_file="packages/aniSearch-Utils-${version}.zip"
          echo "VERSION=${version}" >> $GITHUB_ENV
          echo "ZIP_FILE=${zip_file}" >> $GITHUB_ENV
      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.release_tag }}
          files: ${{ env.ZIP_FILE }}
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
